### ISSUE TITLE
Klasse Gerade schreiben

### ISSUE THREAD

**Issue by thkwalter** [thkwalter/schlupfbezifferung#13]
## Umfang 
* Die Gerade wird definiert durch einen Betriebspunkt und ihre Steigung

## Teilaufgaben
* [ ] Konstruktor `Gerade(IBetriebspunkt, IBetriebspunkt)` schreiben #14
* [ ] Konstruktor `Gerade(IBetriebspunkt, double)` schreiben #15
* [ ] Methode `Punkt schnittpunktBerechnen(Gerade)` schreiben #16
