### ISSUE TITLE
Klasse Schlupfbezifferung schreiben

### ISSUE THREAD

**Issue by thkwalter** [thkwalter/schlupfbezifferung#4]
## Umfang
* Schlupfbezifferung ausführen

## Teilaufgaben
* [ ] Konstruktor `Schlupfbezifferung(Betriebspunkt, Betriebspunkt, Ortskurve)` schreiben #12
* [x] Methode `fusspunktBerechnen(Ortskurve)` schreiben #5 
* [ ] Methode `inversionszentrumBerechnen(Ortskurve, Betriebspunkt)' schreiben #11

## Anmerkungen
* Im Konstruktor wird die Schlupfbezifferung ausgeführt
