### ISSUE TITLE
Schlupfbezifferung durchführen

### ISSUE THREAD

**Issue by thkwalter** [thkwalter/schlupfbezifferung#8]
## Aufgaben
* [ ] Konstruktor `Gerade(IBetriebspunkt, double)` schreiben #14
* [ ] Konstruktor `Gerade(IBetriebspunkt, IBetriebspunkt)` schreiben #15
* [ ] Konstruktor `Punkt(double, double)` schreiben #17
* [ ] Methode `Punkt schnittpunktBerechnen(Gerade)` schreiben #16
