### ISSUE TITLE
Schlupfbezifferung ausführen

### ISSUE THREAD

**Issue by thkwalter** [thkwalter/schlupfbezifferung#9]
## Aufgaben
* [ ] Klasse `Schlupfbezifferung` schreiben #4
* [x] Klasse `TestdatenOrtskurve` schreiben #7
* [ ] Klasse `Gerade` schreiben #13
